List<Map<String, dynamic>> getInf = [
  {
    'id': 0,
    'name': 'Genshin',
    'developer': 'miHoYo',
    'genre': 'Role-Playing, Action RPG',
    "connectivity": "Online",
    'award1': '#6 Most Discussed PC Game of 2020',
    'award2': '#16 Most Discussed PS4 Game of 2020',
    "yurl1": "https://www.youtube.com/c/EakesTV",
    "yurl2": "https://www.youtube.com/c/MTashed/videos",
    "yname1": "Eakes.com",
    "yname2": "Mtashed.com",
    "turl1": "https://www.twitch.tv/enviosity",
    "turl2": "https://www.twitch.tv/tectone",
    "tname1": "Enviosity.com",
    "tname2": "Tectone.com",
    "wurl1": "https://www.ign.com/wikis/genshin-impact/Walkthrough",
    "wurl2": "https://gamewith.net/genshin-impact/article/show/22408",
    "wname1": "IGN.com",
    "wname2": "GameWith.com",
  },
  {
    'id': 1,
    'name': 'League Of Legend',
    'developer': 'Riot Games',
    'genre': 'Role-Playing, Strategy, Action RPG, Real-Time, MOBA, MOBA',
    "connectivity": "Online",
    'award1': '#2 Most Discussed PC Game of 2009',
    'award2': '#55 Best PC Game of 2009',
    "yurl1":
        "https://www.youtube.com/channel/UCWVz07amFIiK8n1HwiJmU1A/featured",
    "yname1": "Sara LoL.com",
    "yurl2": "https://www.youtube.com/c/Godzu",
    "yname2": "Godzu.com",
    "turl1": "https://www.twitch.tv/lec",
    "tname1": "LEC.com",
    "turl2": "https://www.twitch.tv/lck_korea",
    "tname2": "LCK_Korea.com",
    "wurl1": "https://tr.op.gg/",
    "wname1": "OP.GG.com",
    "wurl2": "https://u.gg/",
    "wname2": "U.gg.com",
  },
  {
    'id': 2,
    'name': 'Red Dead Redemption 2',
    'developer': 'Rockstar Games',
    'genre': 'Action Adventure, Open-World',
    "connectivity": "Online",
    'award1': '#1 Best PS4 Game of 2018',
    'award2': '#1 Most Discussed Xbox One Game of 2018',
    "yurl1": "https://www.youtube.com/c/RedDeadSaloon",
    "yname1": "Red Dead Saloon.com",
    "yurl2": "https://www.youtube.com/user/Zynxize",
    "yname2": "Zynxize.com",
    "turl1": "https://www.twitch.tv/valle",
    "tname1": "Valle.com",
    "turl2":
        "https://www.twitch.tv/luke4316live/videos?category=493959&filter=archives&sort=time",
    "tname2": "luke4316live.com",
    "wurl1": "https://reddead.fandom.com/wiki/Missions_in_Redemption_2",
    "wname1": "FANDOM.com",
    "wurl2":
        "https://guides.gamepressure.com/red-dead-redemption-2/guide.asp?ID=46975",
    "wname2": "GAMEPRESSURE.com",
  },
  {
    'id': 3,
    'name': 'Rocket League',
    'developer': 'Psyonix',
    'genre': 'Racing, Futuristic, Sports, Team, Soccer, Arcade',
    "connectivity": "Online",
    'award1': '#12 Most Discussed PS4 Game of 2015',
    'award2': '#15 Most Discussed PC Game of 2015',
    "yurl1": "https://www.youtube.com/channel/UC0uyIp2gZLLicZbtqn7ZPVQ",
    "yname1": "Sam.com",
    "yurl2": "https://www.youtube.com/channel/UCkNYoWK1LqjFhxYI6BM_kOA",
    "yname2": "Lethamyr.com",
    "turl1": "https://www.twitch.tv/rocketbaguette",
    "tname1": "RocketBaguette.com",
    "turl2": "https://www.twitch.tv/RocketLeagueAPAC",
    "tname2": "RocketLeagueAPAC.com",
    "wurl1": "https://rl.insider.gg/en/",
    "wname1": "ROCKET LEAGUE INSIDER.com",
    "wurl2": "https://rocket-league.com/",
    "wname2": "RL GARAGE.com",
  },
  {
    'id': 4,
    'name': 'Sea Of Theieves',
    'developer': 'Rare Ltd.',
    'genre': 'Racing, Futuristic, Sports, Team, Soccer, Arcade',
    "connectivity": "Online",
    'award1': '#2 Most Discussed Xbox One Game of 2018',
    'award2': '#7 Most Discussed PC Game of 2018',
    "yurl1": "https://www.youtube.com/channel/UC6uQxRwVjOA9FxMHvrDubbw",
    "yname1": "MeshalKhaled.com",
    "yurl2": "https://www.youtube.com/c/Hitbotc",
    "yname2": "HitboTC.com",
    "turl1": "https://www.twitch.tv/meshalkhaledx",
    "tname1": "meshalkhaledx",
    "turl2": "https://www.twitch.tv/summit1g",
    "tname2": "summit1g.com",
    "wurl1": "https://rarethief.com/",
    "wname1": "Rare Thief.com",
    "wurl2": "https://seaofthieves.fandom.com/wiki/Quests",
    "wname2": "FANDOM.com",
  },
  {
    'id': 5,
    'name': 'Titan Fall 2',
    'developer': 'Respawn Entertainment',
    'genre': 'Action, Shooter, First-Person, Arcade',
    "connectivity": "Online",
    'award1': '#6 Best PS4 Game of 2016',
    'award2': '#8 Most Discussed PC Game of 2016',
    "yurl1": "https://www.youtube.com/user/GameInReview1",
    "yname1": "Paper Cut2U Gaming.com",
    "yurl2": "https://www.youtube.com/user/IniquityGames",
    "yname2": "Iniquity Games.com",
    "turl1": "https://www.twitch.tv/bryonato",
    "tname1": "bryonato.com",
    "turl2": "https://www.twitch.tv/astraeustf",
    "tname2": "AstraeusTF.com",
    "wurl1":
        "https://titanfall.fandom.com/wiki/Category:Titanfall_2_Campaign_Missions",
    "wname1": "FANDOM.com",
    "wurl2":
        "https://www.ign.com/wikis/titanfall-2/Walkthrough#Titanfall_2_Complete_Walkthrough",
    "wname2": "IGN.com",
  },
];
